pub mod args;
pub mod bootstrap;
pub mod config;
pub mod diag_source;
pub mod diff;
pub mod dispatch;
pub mod edit_apply;
pub mod map_registry;
pub mod naming;
pub mod patch_selector;
pub mod path_sandbox;
pub mod post_execution;
pub mod preview_token;
pub mod protocol;
pub mod protocol_keys;
pub mod query_resolver;
pub mod registry;
pub mod render_context;
pub mod runner;
pub mod template;
pub mod validate;
pub mod working_tree;

pub const RESULT_BEGIN: &str = "__CODEMOD_RESULT_BEGIN__";
pub const RESULT_END: &str = "__CODEMOD_RESULT_END__";
